/*
Author: Harry Papanicolaou
Date: 14/04/2026

This code reads in the data line of a IBM Model F keyboard on the falling edge of its clock, but is also kinda a playground to mess with things.
This code was used to determine the structure of the keystroke codes generated by the keyboard.
Once the structure was understood it was used to probe the board to understand how to write the lookup table, as well as general testing.
guided by information from https://github.com/tmk/tmk_keyboard/wiki/IBM-PC-XT-Keyboard-Protocol#8088-irq1interrupt-09h

TODO:
Why does the first keystroke LSB output as 1 on (not boot) POWER ON
Write a lookup table
Why does the random data output occur?
NOTE: where the "0 INS" key should be (where . Del is now) is a dead key. Scroll Lock is also the broken
*/



// Setting the GPIO pin numbers for the clk and data lines. For my purposes GPIO12 is clk and GPIO13 is da.
int keyboard_clk = 25;   // Sets the keyboard clock pin to pin number 25
int keyboard_data = 26;  // Sets the keyboard datas pin to pin number 26
//Note: Keeping these both ints because like I dont want to fuckaround and find out

// The character code that the keyboard sends is in this variable.
uint16_t output_character_code = 0; /* Data format as: UP/DOWN bit, 8-bit key identifier, end bit (0). To store all values we need 2 bytes, but its only ever 10 bits.
Realistically this cant be 8 bits because the down/up bit in the code cannot be ignored, so we need at least 9 bits
So on interrupt we should read in data and feed the last integer of data out into the serial port.
*/

int data_bit_number = 0;  // Which bit of data are we reading. Only goes up to 10 so like we really dont need anything big.


// the setup routine runs once when you press reset:

void IRAM_ATTR clock_falling_edge() {
  output_character_code = output_character_code + (digitalRead(keyboard_data) << data_bit_number);  //How it should be
  data_bit_number++;                                                                                //increment the bit by 1. If it reaches 10, we need to reset it.
}

/* Update: Uint8 is too small
  Actually every last bit appears to be 0, so thats the end bit code and it seems we are missing the MSB
*/

void setup() {
  // initialize serial communication at 115200 bits per second:
  //supposedly instructions happen once every 2.5 uS = 400 000 times a second

  Serial.begin(115200);  //TODO: Maybe the baud rate needs to be upped? I think scaling it makes sense, but lets be sure about that first.

  // Set the pins to inputs/interrupts:

  pinMode(keyboard_clk, INPUT);  //This is an INPUT pin because the keyboard actually generates the clock, so we get to sample this side.
  attachInterrupt(keyboard_clk, clock_falling_edge, FALLING);

  pinMode(keyboard_data, INPUT);
}


// the loop routine runs over and over again forever:
void loop() {

  if (data_bit_number >= 10) {
    Serial.println(output_character_code, BIN);  //Output the full data of the code
    //Type 3 - if output_character_code is uint8_t then it just cuts off the start bits because of how this shit works. CANT USE FREAKY MODE.

    data_bit_number = 0;
    output_character_code = 0;
  }
}
